version: '3.9'

services:
  api:
    volumes:
    - .:/app/
    ports:
    - "8000:8000"
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: dev
    image: app:${APP_VERSION:-latest}
    restart: unless-stopped
    # env_file:
    # - .env
    environment:
      APP_RELOAD: "True"
